spring:
  application:
    name: interview
  datasource:
    url: jdbc:h2:mem:///texodb
    username: root
    password: admin
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

cloud:
  aws:
    cognito:
      user-pool-id: test
      api-client: test